GET http://localhost:3000/

###

GET http://localhost:3000/api/user/

###

POST http://localhost:3000/api/user/register/
content-type: application/json

{
    "name": "lishugupta",
    "email": "lishu@pakkabaniya.ml",
    "password" : "iamunabletotype"
}


###

POST http://localhost:3000/api/user/login/
content-type: application/json

{
    "email": "lishu@pakkabaniya.ml",
    "password" : "iamunabletotype"
}